export const quiz_example = {
  "question_type":"multiple_choice",
  "choices":[
    {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/facebook.png",
      "score":15,
      "answer":true,
      "index":0,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"Para identificar este tipo de casos, debes fijarte bien en la dirección de correo del remitente y los redireccionamientos de los enlaces en el correo.",
    }, {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/santander.jpg",
      "score":20,
      "answer":true,
      "index":1,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"Si te fijas en el enlace, a pesar de poner www.santanderrio.com.ar, te redirije a una página desconocida y que no pertenece al Santander.",
    }, {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/netflix.jpg",
      "score":15,
      "answer":false,
      "index":2,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Este correo fue enviado por Netflix debido a un caso de Phishing que sufrieron a principios de 2018.",
    }, {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/outlook.jpg",
      "score":30,
      "answer":true,
      "index":3,
      "answered":false,
      "feedback":"Es verdadero, el correo desde el que se envía el mensaje no es propio de Outlook y, como puedes ver, el enlace te lleva a una página desconocida",
    },
  ],
};

export const quiz_example2 = {
  "question_type":"multiple_choice",
  "choices":[
    {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/StephenHawking.png",
      "score":15,
      "answer":false,
      "index":0,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Además de ser un titular un tanto inverosimil, El Mundo Today es un diario en tono satírico que crea noticias para parodiar la realidad.",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/pegado.png",
      "score":20,
      "answer":true,
      "index":1,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"A pesar de ser surrealista, esto pasó en Malasia. Si te fijas, en la parte de abajo aparece ABC.ES",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/bieber.jpg",
      "score":15,
      "answer":false,
      "index":2,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Este correo fue enviado por Netflix debido a un caso de Phishing que sufrieron a principios de 2018.",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/alcohol.png",
      "score":30,
      "answer":true,
      "index":3,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"Ocurrió en el verano de 2016 y el conductor dio 4.75 gramos por litro en sangre. De nuevo, esta noticia es de ABC.ES",
    },
  ],
};
