export const quiz_example = {
  "question_type":"multiple_choice",
  "choices":[
    {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/phishing/facebook.png",
      "score":15,
      "answer":true,
      "index":0,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"Para identificar este tipo de casos, debes fijarte bien en la dirección de correo del remitente y los redireccionamientos de los enlaces en el correo.",
    }, {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/phishing/santander.jpg",
      "score":25,
      "answer":true,
      "index":1,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"Si te fijas en el correo del remitente, la dirección no pertenece al Banco Santander sino que es de un dominio desconocido.",
    }, {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/phishing/netflix.jpg",
      "score":30,
      "answer":false,
      "index":2,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Este correo fue enviado por Netflix debido a un caso de Phishing que sufrieron a principios de 2018.",
    }, {
      "title":"¿Se trata de un caso de Phishing?",
      "img":"./assets/images/phishing/outlook.jpg",
      "score":30,
      "answer":true,
      "index":3,
      "answered":false,
      "feedback_answer":"Verdadero!",
      "feedback_text":"El correo desde el que se envía el mensaje no es propio de Outlook y, como puedes ver, el enlace te lleva a una página desconocida",
    },
  ],
};

export const quiz_example2 = {
  "question_type":"multiple_choice",
  "choices":[
    {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/news/StephenHawking.png",
      "score":25,
      "answer":false,
      "index":0,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Además de ser un titular un tanto inverosimil, El Mundo Today es un diario en tono satírico que crea noticias para parodiar la realidad.",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/news/pegado.png",
      "score":40,
      "answer":true,
      "index":1,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"A pesar de ser surrealista, esto pasó en Malasia. Si te fijas, en la parte de abajo aparece ABC.ES",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/news/alcohol.jpg",
      "score":35,
      "answer":false,
      "index":2,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Ocurrió en el verano de 2016 y el conductor dio 4.75 gramos por litro en sangre. De nuevo, esta noticia es de ABC.ES",
    },
  ],
};

export const quiz_example3 = {
  "question_type":"multiple_choice",
  "choices":[
    {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/StephenHawking.png",
      "score":15,
      "answer":false,
      "index":0,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Además de ser un titular un tanto inverosimil, El Mundo Today es un diario en tono satírico que crea noticias para parodiar la realidad.",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/pegado.png",
      "score":20,
      "answer":true,
      "index":1,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"A pesar de ser surrealista, esto pasó en Malasia. Si te fijas, en la parte de abajo aparece ABC.ES",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/bieber.jpg",
      "score":15,
      "answer":false,
      "index":2,
      "answered":false,
      "feedback_answer":"Falso",
      "feedback_text":"Este correo fue enviado por Netflix debido a un caso de Phishing que sufrieron a principios de 2018.",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/alcohol.png",
      "score":30,
      "answer":true,
      "index":3,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"Ocurrió en el verano de 2016 y el conductor dio 4.75 gramos por litro en sangre. De nuevo, esta noticia es de ABC.ES",
    }, {
      "title":"¿Verdadero o falso?",
      "img":"./assets/images/alcohol.png",
      "score":30,
      "answer":true,
      "index":4,
      "answered":false,
      "feedback_answer":"Verdadero",
      "feedback_text":"Ocurrió en el verano de 2016 y el conductor dio 4.75 gramos por litro en sangre. De nuevo, esta noticia es de ABC.ES",
      },
  ],
};
